{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ConnectionError","kind":"identifier"}]}]}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/network(_:)","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/unknown(isProtected:)"],"title":"Enumeration Cases","anchor":"Enumeration-Cases"},{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/errorDescription"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/Error-Implementations","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/LocalizedError-Implementations"],"anchor":"Default-Implementations","generated":true,"title":"Default Implementations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pulse\/remotelogger\/connectionerror"]}],"sections":[],"metadata":{"externalID":"s:5Pulse12RemoteLoggerC15ConnectionErrorO","modules":[{"name":"Pulse"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConnectionError"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ConnectionError","kind":"identifier"}],"title":"RemoteLogger.ConnectionError","symbolKind":"enum","roleHeading":"Enumeration"},"hierarchy":{"paths":[["doc:\/\/com.github.pulse\/documentation\/Pulse","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger"]]},"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.github.pulse\/10Foundation14LocalizedErrorP","doc:\/\/com.github.pulse\/s5ErrorP","doc:\/\/com.github.pulse\/s8SendableP"],"kind":"relationships"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/errorDescription":{"type":"topic","role":"symbol","title":"errorDescription","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/errorDescription","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorDescription"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/pulse\/remotelogger\/connectionerror\/errordescription","abstract":[]},"doc://com.github.pulse/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.github.pulse\/s8SendableP"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/network(_:)":{"kind":"symbol","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/network(_:)","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"network"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NWError","preciseIdentifier":"s:7Network7NWErrorO"},{"text":")","kind":"text"}],"title":"RemoteLogger.ConnectionError.network(_:)","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/network(_:)","abstract":[],"type":"topic"},"doc://com.github.pulse/s5ErrorP":{"type":"unresolvable","identifier":"doc:\/\/com.github.pulse\/s5ErrorP","title":"Swift.Error"},"doc://com.github.pulse/10Foundation14LocalizedErrorP":{"type":"unresolvable","identifier":"doc:\/\/com.github.pulse\/10Foundation14LocalizedErrorP","title":"Foundation.LocalizedError"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError":{"navigatorTitle":[{"kind":"identifier","text":"ConnectionError"}],"type":"topic","kind":"symbol","abstract":[],"title":"RemoteLogger.ConnectionError","role":"symbol","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError","url":"\/documentation\/pulse\/remotelogger\/connectionerror","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConnectionError"}]},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/LocalizedError-Implementations":{"type":"topic","kind":"article","title":"LocalizedError Implementations","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/localizederror-implementations","role":"collectionGroup","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/LocalizedError-Implementations","abstract":[]},"doc://com.github.pulse/documentation/Pulse":{"title":"Pulse","url":"\/documentation\/pulse","abstract":[{"text":"Logger and network inspector for Apple platforms.","type":"text"}],"role":"collection","type":"topic","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse","kind":"symbol"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/unknown(isProtected:)":{"abstract":[],"role":"symbol","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/unknown(isprotected:)","type":"topic","title":"RemoteLogger.ConnectionError.unknown(isProtected:)","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"unknown","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isProtected","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/unknown(isProtected:)"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger":{"navigatorTitle":[{"kind":"identifier","text":"RemoteLogger"}],"url":"\/documentation\/pulse\/remotelogger","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RemoteLogger","kind":"identifier"}],"kind":"symbol","title":"RemoteLogger","abstract":[{"type":"text","text":"Connects to the remote server and sends logs remotely. In the current version,"},{"text":" ","type":"text"},{"type":"text","text":"a server is a Pulse Pro app for macOS)."}],"role":"symbol"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/Error-Implementations":{"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/Error-Implementations","abstract":[],"type":"topic","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/error-implementations","kind":"article","role":"collectionGroup","title":"Error Implementations"}}}