{"metadata":{"title":"RemoteLogger.ConnectionError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ConnectionError","kind":"identifier"}],"navigatorTitle":[{"text":"ConnectionError","kind":"identifier"}],"symbolKind":"enum","role":"symbol","externalID":"s:5Pulse12RemoteLoggerC15ConnectionErrorO","roleHeading":"Enumeration","modules":[{"name":"Pulse"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConnectionError","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"identifiers":["doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/network(_:)","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/unknown(isProtected:)"],"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases"},{"title":"Instance Properties","identifiers":["doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/errorDescription"],"generated":true,"anchor":"Instance-Properties"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/Error-Implementations","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/LocalizedError-Implementations"],"anchor":"Default-Implementations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pulse\/remotelogger\/connectionerror"]}],"hierarchy":{"paths":[["doc:\/\/com.github.pulse\/documentation\/Pulse","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger"]]},"sections":[],"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.github.pulse\/10Foundation14LocalizedErrorP","doc:\/\/com.github.pulse\/s5ErrorP","doc:\/\/com.github.pulse\/s8SendableP"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"references":{"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/LocalizedError-Implementations":{"title":"LocalizedError Implementations","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/LocalizedError-Implementations","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/localizederror-implementations","abstract":[],"role":"collectionGroup","type":"topic","kind":"article"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger":{"abstract":[{"type":"text","text":"Connects to the remote server and sends logs remotely. In the current version,"},{"type":"text","text":" "},{"text":"a server is a Pulse Pro app for macOS).","type":"text"}],"role":"symbol","url":"\/documentation\/pulse\/remotelogger","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RemoteLogger","kind":"identifier"}],"kind":"symbol","title":"RemoteLogger","navigatorTitle":[{"kind":"identifier","text":"RemoteLogger"}],"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger"},"doc://com.github.pulse/documentation/Pulse":{"kind":"symbol","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse","url":"\/documentation\/pulse","abstract":[{"type":"text","text":"Logger and network inspector for Apple platforms."}],"type":"topic","title":"Pulse","role":"collection"},"doc://com.github.pulse/10Foundation14LocalizedErrorP":{"type":"unresolvable","identifier":"doc:\/\/com.github.pulse\/10Foundation14LocalizedErrorP","title":"Foundation.LocalizedError"},"doc://com.github.pulse/s5ErrorP":{"type":"unresolvable","identifier":"doc:\/\/com.github.pulse\/s5ErrorP","title":"Swift.Error"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/network(_:)":{"role":"symbol","type":"topic","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/network(_:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"network"},{"text":"(","kind":"text"},{"text":"NWError","kind":"typeIdentifier","preciseIdentifier":"s:7Network7NWErrorO"},{"kind":"text","text":")"}],"title":"RemoteLogger.ConnectionError.network(_:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/network(_:)"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/errorDescription":{"title":"errorDescription","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/errorDescription","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/errordescription","abstract":[],"role":"symbol","type":"topic","kind":"symbol"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError":{"role":"symbol","navigatorTitle":[{"text":"ConnectionError","kind":"identifier"}],"type":"topic","url":"\/documentation\/pulse\/remotelogger\/connectionerror","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConnectionError"}],"title":"RemoteLogger.ConnectionError","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/unknown(isProtected:)":{"role":"symbol","type":"topic","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/unknown(isprotected:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknown"},{"text":"(","kind":"text"},{"text":"isProtected","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"title":"RemoteLogger.ConnectionError.unknown(isProtected:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/unknown(isProtected:)"},"doc://com.github.pulse/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/com.github.pulse\/s8SendableP","type":"unresolvable"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/Error-Implementations":{"role":"collectionGroup","type":"topic","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/error-implementations","title":"Error Implementations","abstract":[],"kind":"article","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/Error-Implementations"}}}