{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Currently is only used for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/PulseCore\/documentation\/PulseCore\/NetworkLogger\/DecodingError"},{"type":"text","text":"."}]}],"type":"aside","name":"Note"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/pulsecore\/networklogger\/responseerror\/error"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/PulseCore\/documentation\/PulseCore\/NetworkLogger\/ResponseError\/error","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Contains the underlying error."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"title":"error","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:9PulseCore13NetworkLoggerC13ResponseErrorV5errors0F0_pSgvp","modules":[{"name":"PulseCore"}]},"hierarchy":{"paths":[["doc:\/\/PulseCore\/documentation\/PulseCore","doc:\/\/PulseCore\/documentation\/PulseCore\/NetworkLogger","doc:\/\/PulseCore\/documentation\/PulseCore\/NetworkLogger\/ResponseError"]]},"references":{"doc://PulseCore/documentation/PulseCore/NetworkLogger":{"role":"symbol","title":"NetworkLogger","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkLogger"}],"abstract":[{"type":"text","text":"A wrapper on top of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/PulseCore\/documentation\/PulseCore\/LoggerStore"},{"type":"text","text":" that simplifies logging of network requests."}],"identifier":"doc:\/\/PulseCore\/documentation\/PulseCore\/NetworkLogger","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NetworkLogger"}],"url":"\/documentation\/pulsecore\/networklogger"},"doc://PulseCore/documentation/PulseCore/NetworkLogger/ResponseError/error":{"role":"symbol","title":"error","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Contains the underlying error."}],"identifier":"doc:\/\/PulseCore\/documentation\/PulseCore\/NetworkLogger\/ResponseError\/error","kind":"symbol","type":"topic","url":"\/documentation\/pulsecore\/networklogger\/responseerror\/error"},"doc://PulseCore/documentation/PulseCore/NetworkLogger/DecodingError":{"role":"symbol","title":"NetworkLogger.DecodingError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DecodingError"}],"abstract":[],"identifier":"doc:\/\/PulseCore\/documentation\/PulseCore\/NetworkLogger\/DecodingError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DecodingError"}],"url":"\/documentation\/pulsecore\/networklogger\/decodingerror"},"doc://PulseCore/documentation/PulseCore":{"role":"collection","title":"PulseCore","abstract":[{"type":"text","text":"Logger and network inspector for Apple platforms."}],"identifier":"doc:\/\/PulseCore\/documentation\/PulseCore","kind":"symbol","type":"topic","url":"\/documentation\/pulsecore"},"doc://PulseCore/documentation/PulseCore/NetworkLogger/ResponseError":{"role":"symbol","title":"NetworkLogger.ResponseError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResponseError"}],"abstract":[],"identifier":"doc:\/\/PulseCore\/documentation\/PulseCore\/NetworkLogger\/ResponseError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResponseError"}],"url":"\/documentation\/pulsecore\/networklogger\/responseerror"},"doc://PulseCore/documentation/PulseCore/LoggerStore":{"role":"symbol","title":"LoggerStore","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggerStore"}],"abstract":[{"type":"text","text":"Persistently stores logs, network requests, and response blobs."}],"identifier":"doc:\/\/PulseCore\/documentation\/PulseCore\/LoggerStore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LoggerStore"}],"url":"\/documentation\/pulsecore\/loggerstore"}}}