{"variants":[{"paths":["\/documentation\/pulse\/remotelogger\/connectionerror\/error-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/Error-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/localizedDescription"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Pulse"}],"role":"collectionGroup","title":"Error Implementations"},"hierarchy":{"paths":[["doc:\/\/com.github.pulse\/documentation\/Pulse","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError"]]},"references":{"doc://com.github.pulse/documentation/Pulse/RemoteLogger":{"role":"symbol","title":"RemoteLogger","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteLogger"}],"abstract":[{"type":"text","text":"Connects to the remote server and sends logs remotely. In the current version,"},{"type":"text","text":" "},{"type":"text","text":"a server is a Pulse Pro app for macOS)."}],"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RemoteLogger"}],"url":"\/documentation\/pulse\/remotelogger"},"doc://com.github.pulse/documentation/Pulse":{"role":"collection","title":"Pulse","abstract":[{"type":"text","text":"Logger and network inspector for Apple platforms."}],"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse","kind":"symbol","type":"topic","url":"\/documentation\/pulse"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError":{"role":"symbol","title":"RemoteLogger.ConnectionError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConnectionError"}],"abstract":[],"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConnectionError"}],"url":"\/documentation\/pulse\/remotelogger\/connectionerror"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/localizedDescription":{"role":"symbol","title":"localizedDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/localizedDescription","kind":"symbol","type":"topic","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/localizeddescription"}}}