{"kind":"article","topicSections":[{"generated":true,"identifiers":["doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/failureReason","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/helpAnchor","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/recoverySuggestion"],"title":"Instance Properties","anchor":"Instance-Properties"}],"metadata":{"title":"LocalizedError Implementations","modules":[{"name":"Pulse"}],"roleHeading":"API Collection","role":"collectionGroup"},"hierarchy":{"paths":[["doc:\/\/com.github.pulse\/documentation\/Pulse","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError"]]},"variants":[{"paths":["\/documentation\/pulse\/remotelogger\/connectionerror\/localizederror-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/LocalizedError-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/recoverySuggestion":{"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/recoverySuggestion","title":"recoverySuggestion","kind":"symbol","type":"topic","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/recoverysuggestion","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError":{"navigatorTitle":[{"kind":"identifier","text":"ConnectionError"}],"type":"topic","kind":"symbol","abstract":[],"title":"RemoteLogger.ConnectionError","role":"symbol","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError","url":"\/documentation\/pulse\/remotelogger\/connectionerror","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConnectionError"}]},"doc://com.github.pulse/documentation/Pulse/RemoteLogger":{"navigatorTitle":[{"kind":"identifier","text":"RemoteLogger"}],"url":"\/documentation\/pulse\/remotelogger","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RemoteLogger","kind":"identifier"}],"kind":"symbol","title":"RemoteLogger","abstract":[{"type":"text","text":"Connects to the remote server and sends logs remotely. In the current version,"},{"text":" ","type":"text"},{"type":"text","text":"a server is a Pulse Pro app for macOS)."}],"role":"symbol"},"doc://com.github.pulse/documentation/Pulse":{"title":"Pulse","url":"\/documentation\/pulse","abstract":[{"text":"Logger and network inspector for Apple platforms.","type":"text"}],"role":"collection","type":"topic","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse","kind":"symbol"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/helpAnchor":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol","title":"helpAnchor","type":"topic","role":"symbol","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/helpanchor","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/helpAnchor","abstract":[]},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/failureReason":{"kind":"symbol","type":"topic","role":"symbol","title":"failureReason","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/failurereason","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/failureReason","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]}}}