{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/pulse\/remotelogger\/connectionerror\/network(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.github.pulse\/documentation\/Pulse","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/network(_:)"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"network","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:7Network7NWErrorO","text":"NWError","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"externalID":"s:5Pulse12RemoteLoggerC15ConnectionErrorO7networkyAE7Network7NWErrorOcAEmF","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"network","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NWError","preciseIdentifier":"s:7Network7NWErrorO"},{"text":")","kind":"text"}],"modules":[{"name":"Pulse"}],"title":"RemoteLogger.ConnectionError.network(_:)","roleHeading":"Case","symbolKind":"case","role":"symbol"},"references":{"doc://com.github.pulse/documentation/Pulse":{"role":"collection","url":"\/documentation\/pulse","kind":"symbol","title":"Pulse","abstract":[{"type":"text","text":"Logger and network inspector for Apple platforms."}],"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse","type":"topic"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/network(_:)":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"network"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NWError","preciseIdentifier":"s:7Network7NWErrorO"},{"kind":"text","text":")"}],"title":"RemoteLogger.ConnectionError.network(_:)","role":"symbol","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/network(_:)","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/network(_:)","abstract":[],"kind":"symbol"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError":{"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError","title":"RemoteLogger.ConnectionError","abstract":[],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConnectionError"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConnectionError"}],"kind":"symbol","url":"\/documentation\/pulse\/remotelogger\/connectionerror"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger":{"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RemoteLogger","kind":"identifier"}],"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger","title":"RemoteLogger","role":"symbol","url":"\/documentation\/pulse\/remotelogger","abstract":[{"type":"text","text":"Connects to the remote server and sends logs remotely. In the current version,"},{"type":"text","text":" "},{"text":"a server is a Pulse Pro app for macOS).","type":"text"}],"navigatorTitle":[{"text":"RemoteLogger","kind":"identifier"}]}}}