{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@NSManaged"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/pulsecore\/loggernetworkrequestentity\/errorcode"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/PulseCore\/documentation\/PulseCore\/LoggerNetworkRequestEntity\/errorCode","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"errorCode","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@PulseCore@objc(cs)LoggerNetworkRequestEntity(py)errorCode","modules":[{"name":"PulseCore"}]},"hierarchy":{"paths":[["doc:\/\/PulseCore\/documentation\/PulseCore","doc:\/\/PulseCore\/documentation\/PulseCore\/LoggerNetworkRequestEntity"]]},"references":{"doc://PulseCore/documentation/PulseCore/LoggerNetworkRequestEntity":{"role":"symbol","title":"LoggerNetworkRequestEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggerNetworkRequestEntity"}],"abstract":[],"identifier":"doc:\/\/PulseCore\/documentation\/PulseCore\/LoggerNetworkRequestEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LoggerNetworkRequestEntity"}],"url":"\/documentation\/pulsecore\/loggernetworkrequestentity"},"doc://PulseCore/documentation/PulseCore/LoggerNetworkRequestEntity/errorCode":{"role":"symbol","title":"errorCode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/PulseCore\/documentation\/PulseCore\/LoggerNetworkRequestEntity\/errorCode","kind":"symbol","type":"topic","url":"\/documentation\/pulsecore\/loggernetworkrequestentity\/errorcode"},"doc://PulseCore/documentation/PulseCore":{"role":"collection","title":"PulseCore","abstract":[{"type":"text","text":"Logger and network inspector for Apple platforms."}],"identifier":"doc:\/\/PulseCore\/documentation\/PulseCore","kind":"symbol","type":"topic","url":"\/documentation\/pulsecore"}}}