{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileAleadyExists"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/pulse\/loggerstore\/error\/filealeadyexists"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/Pulse\/documentation\/Pulse\/LoggerStore\/Error\/fileAleadyExists","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileAleadyExists"}],"title":"LoggerStore.Error.fileAleadyExists","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:5Pulse11LoggerStoreC5ErrorO16fileAleadyExistsyA2EmF","modules":[{"name":"Pulse"}]},"hierarchy":{"paths":[["doc:\/\/Pulse\/documentation\/Pulse","doc:\/\/Pulse\/documentation\/Pulse\/LoggerStore","doc:\/\/Pulse\/documentation\/Pulse\/LoggerStore\/Error"]]},"references":{"doc://Pulse/documentation/Pulse/LoggerStore/Error/fileAleadyExists":{"role":"symbol","title":"LoggerStore.Error.fileAleadyExists","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileAleadyExists"}],"abstract":[],"identifier":"doc:\/\/Pulse\/documentation\/Pulse\/LoggerStore\/Error\/fileAleadyExists","kind":"symbol","type":"topic","url":"\/documentation\/pulse\/loggerstore\/error\/filealeadyexists"},"doc://Pulse/documentation/Pulse/LoggerStore":{"role":"symbol","title":"LoggerStore","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggerStore"}],"abstract":[{"type":"text","text":"Persistently stores logs, network requests, and response blobs."}],"identifier":"doc:\/\/Pulse\/documentation\/Pulse\/LoggerStore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LoggerStore"}],"url":"\/documentation\/pulse\/loggerstore"},"doc://Pulse/documentation/Pulse/LoggerStore/Error":{"role":"symbol","title":"LoggerStore.Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"abstract":[],"identifier":"doc:\/\/Pulse\/documentation\/Pulse\/LoggerStore\/Error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Error"}],"url":"\/documentation\/pulse\/loggerstore\/error"},"doc://Pulse/documentation/Pulse":{"role":"collection","title":"Pulse","abstract":[{"type":"text","text":"Logger and network inspector for Apple platforms."}],"identifier":"doc:\/\/Pulse\/documentation\/Pulse","kind":"symbol","type":"topic","url":"\/documentation\/pulse"}}}